### ISSUE TITLE
Panic after moving around the mouse in window of adventure example

### ISSUE THREAD

**Issue by robbycerantola** [redox-os/orbgame#11]
When running the adventure example, if you move around the mouse for a while ( doing so only then the sprite is animated because of orbclient issue #41 ) error shows up:
```
thread 'main' panicked at 'index out of bounds: the len is 16 but the index is 16', /checkout/src/liballoc/vec.rs:1551:10
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic_bounds_check
             at libcore/panicking.rs:58
  10: orbgame::scene::Scene::draw_all_layers
  11: orbtk::window::Window::draw_widget
  12: orbtk::window::Window::draw
  13: orbgame::game::Game::exec
  14: adventure::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  19: main
  20: __libc_start_main
  21: _start
```

**Comment by robbycerantola** [comment]
After PR #12 it panics after the first sprite animation. It seems that animation does not start over and try to access next frame that does not exists. Untill I move the sprite around there is no panic.

**Comment by FloVanGH** [comment]
I've pushed an quick fix for the crash. But the palyer.hrai still needs an update for correct animation calculation. I'll do it next week.
